import Head from "next/head";
import { Header, Main, MyWork, Book, Footer } from "components";
//

export default function Home() {
    return (
        <div>
            <Head>
                <title>Frontend Mentor | Single-page design portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/assets/favicon-32x32.png" />
            </Head>

            <Header />
            <Main />
            <MyWork />
            <Book />
            <Footer />
        </div>
    );
}
